### ISSUE TITLE
Chat reading

### ISSUE THREAD

**Issue by TheMetabee** [d0lb33/TimerTracker#3]
Hey. I'm looking to use your project as inspiration to make something similar. Recently, there's been a "maybe" coming from Riot that we can use timers similar to how China has their very own official ingame timer tracking software. I'm probably going to write this all in C#, but was looking to ask how would I go about reading the chat for commands like "/n Ez f" or even just parsing it in real time? I want to be able to do stuff like "blue frog camp" and then my program would immediately put a visible timer to show when it's back up. Or at least giving me a place to start where I can read data from the game (the public visible kind that everyone has access to).

**Comment by d0lb33** [comment]
You can find this information located in the text file for notes. You’d have to say /note blue frog camp for this to work. I’ve been extremely busy with schoolwork so I’ve not had time to help many people who message me. But let me know if that helps!

**Comment by TheMetabee** [comment]
I've been looking at your code in Visual Studio. Are you essentially just having the player type into your form, which is always in the front, and then it's saved to a text file, which then is read and the timers are updated accordingly? If so, it makes a lot more sense.

**Comment by d0lb33** [comment]
It’s located in the Riot Games folder. You can do a search for it and it should be under “MyNotes.txt”

**Comment by TheMetabee** [comment]
I see what you're doing now. I wasn't aware of the /n text command in game. Funny how such a small change makes a big difference. I know how to proceed now. Thank you.
